spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST}:3306/${DB_NAME}"
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Options: none, update, create, create-drop
    show-sql: true  # Enable query logging
    properties:
      hibernate:
        format_sql: true  # Pretty-print SQL logs

server:
  port: 9090
